title: Marko A. Rodriguez
email: marko@markorodriguez.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://markorodriguez.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twarko
github_username:  okram

# Build settings
theme: minima
plugins:
  - jekyll-feed
